apiVersion: v1
kind: Service
metadata:
    name: orchestrator-portal
spec:
    type: ClusterIP
    selector:
        component: orchestrator-portal
    ports:
      - port: 80
        targetPort: 8080
        protocol: TCP