apiVersion: v1
kind: Service
metadata:
    name: dataservices
spec:
    type: ClusterIP
    selector:
        component: dataservices
    ports:
      # authenticated traffic
      - name: authenticated
        port: 80
        targetPort: 8080
        protocol: TCP
      # unauthenticated traffic
      - name: unauthenticated
        port: 81
        targetPort: 8081
        protocol: TCP