apiVersion: v1
kind: Service
metadata:
    name: conductor
spec:
    type: ClusterIP
    selector:
        component: conductor
    ports:
      - port: 80
        targetPort: 8080
        protocol: TCP